apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  # annotations:
    # external-dns.alpha.kubernetes.io/hostname: devopstube.com
    # external-dns.alpha.kubernetes.io/ttl: "120" #optiona  
  namespace: argo-devops
spec:
  ports:
  - name: nginx-ui
    port: 80
    targetPort: 80
  selector:
    name: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: ui