apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: devopstube.com
    external-dns.alpha.kubernetes.io/ttl: "120" #optiona  
  namespace: default
spec:
  ports:
  - name: wordpress-ui
    port: 80
    targetPort: 80
  selector:
    name: wordpress
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: argo-devops
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - image: wordpress
        imagePullPolicy: IfNotPresent
        name: wordpress
        ports:
        - containerPort: 80
          name: ui